spring:
  datasource:
    url: jdbc:postgresql://localhost:8112/map
    username: SuperUser
    password: stronk-pazzward
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
