spring:
  datasource:
    url: jdbc:postgresql://localhost:8112/map
    username: SuperUser
    password: stronk-pazzward
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false
